### ISSUE TITLE
Footer not displayed on Mobile View

### ISSUE THREAD

**Issue by ThiruPraveen18** [Vrijraj/GDGx-Event-Web-App#3]
The Footer part does not show up on Mobile responsive view.

**Comment by Vrijraj** [comment]
Can you please share the screenshot

**Comment by ThiruPraveen18** [comment]
![Website Screenshot](https://user-images.githubusercontent.com/38263565/44908682-05b11580-ad3a-11e8-94d5-f2cb3e5fcca6.jpg)
![Website Screenshot](https://user-images.githubusercontent.com/38263565/44908684-0649ac00-ad3a-11e8-90a7-68978b5f135e.jpg)

**Comment by Vrijraj** [comment]
If the screen **width <990px then the footer navigation will be visible** otherwise we have a **header and its navigation menu.**
We're working on it to improve the UI.
 
Thanks for the information.
